// Mocks generated by Mockito 5.4.3 from annotations
// in forgotten_key/test/util/char_game_info_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:forgotten_key/models/char_game_info.dart' as _i3;
import 'package:forgotten_key/util/char_game_info_reader.dart' as _i4;
import 'package:loggy/loggy.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoggy_0<T extends _i1.LoggyType> extends _i2.SmartFake
    implements _i1.Loggy<T> {
  _FakeLoggy_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharGameInfo_1 extends _i2.SmartFake implements _i3.CharGameInfo {
  _FakeCharGameInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CharGameInfoReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharGameInfoReader extends _i2.Mock
    implements _i4.CharGameInfoReader {
  MockCharGameInfoReader() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  _i1.Loggy<_i1.UiLoggy> get loggy => (super.noSuchMethod(
        Invocation.getter(#loggy),
        returnValue: _FakeLoggy_0<_i1.UiLoggy>(
          this,
          Invocation.getter(#loggy),
        ),
      ) as _i1.Loggy<_i1.UiLoggy>);

  @override
  _i6.Future<_i3.CharGameInfo> read() => (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
        ),
        returnValue: _i6.Future<_i3.CharGameInfo>.value(_FakeCharGameInfo_1(
          this,
          Invocation.method(
            #read,
            [],
          ),
        )),
      ) as _i6.Future<_i3.CharGameInfo>);
}
